### ISSUE TITLE
License was removed. What license is used now?

### ISSUE THREAD

**Issue by IzzySoft** [flyt3e/tainer_app#26]
I see you've [removed the license](https://github.com/flyt3e/tainer_app/commit/94dbf220a851ef5a69e163e3c2baa7ab9df71592) recently. What license is your app using now? Without any license being declared, it falls back to "all rights reserved" and thus is no longer F/LOSS (free, libre open-source software), all rights are removed from the user. The code being available here then only means it can be looked at. It doesn't meet the Linux philosophy either then. As a result, I'll have to [remove it from my repo](https://apt.izzysoft.de/fdroid/index/apk/me.flytree.tainer).

So is there any chance you put the app under a FOSS license in the near future again? Thanks for caring!

**Comment by Flytreels** [comment]
Right now the app is still in early development, later on the app I will re-develop using Kotlin and Jetpack Compose, the license will still be GPLv3
Thanks for caring this app! I am so happy to see these

**Comment by Flytreels** [comment]
and thank you very much, you upload the app to fdroid, but I suggest you don't do it now because I will rewrite the whole app (including UI) in July, so this will change a lot

**Comment by Flytreels** [comment]
I always GUARANTEE that I will always be GPLV3

**Comment by IzzySoft** [comment]
Hi @Flytreels and thanks for your prompt reply! The app is not on F-Droid (just in my repo), so no worries. Thanks for re-establishing the license, and for keeping your app FOSS!

**Comment by Flytreels** [comment]
thanks alot
